server:
    port: 8080

#management:
#    endpoint.gateway.enabled: true
#    endpoints.web.exposure.include: gateway
    
spring:
    application:
        name: gateway-service  
    cloud:
        gateway:
#            actuator.verbose.enabled: false
            routes:
                - id: openapi
                  uri: http://localhost:${server.port}
                  predicates:
                    - Path=/v3/api-docs/**
                  filters:
                    - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs/
                    
                - id: hello-service
                  uri: http://localhost:15000/
                  predicates:
                    - Path=/hello/**
                  filters:
                    - RewritePath=/hello/v3/api-docs/, /v3/api-docs/

                - id: goodbye-service
                  uri: http://localhost:15001/
                  predicates:
                    - Path=/goodbye/**
                  filters:
                    - RewritePath=/goodbye/v3/api-docs/, /v3/api-docs/